name: PR Check

on:
  pull_request:
    branches: [test]

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.8.0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm dlx playwright install --with-deps

      - name: Set up .env file for database
        run: |
          echo "POSTGRES_DB=${{ vars.POSTGRES_DB }}" >> ./packages/database/.env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> ./packages/database/.env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> ./packages/database/.env
          echo "DATABASE_URL=${{ vars.DATABASE_URL }}" >> ./packages/database/.env

      - name: Run database setup
        run: |
          pnpm exec turbo db:start
          pnpm exec turbo db:migrate

      #- name: Run Unit Tests
      #  run: pnpm exec turbo test

      - name: Run E2E Tests
        run: |
          pnpm exec turbo e2e:run

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30